# Generated by Django 5.2.13 on 2026-04-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dining_date', models.DateTimeField(verbose_name='就餐时间')),
                ('party_size', models.PositiveIntegerField(default=1, verbose_name='就餐人数')),
                ('table_number', models.CharField(blank=True, default='', max_length=20, verbose_name='桌号')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='消费金额')),
                ('dishes', models.JSONField(blank=True, default=dict, help_text='JSON格式，如 [{"name":"宫保鸡丁","price":38,"qty":1}]', verbose_name='点菜记录')),
                ('satisfaction', models.PositiveIntegerField(blank=True, help_text='1-5分', null=True, verbose_name='满意度')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_records', to='customers.customer', verbose_name='客户')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dining_records', to='customers.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '就餐记录',
                'verbose_name_plural': '就餐记录',
                'ordering': ['-dining_date'],
            },
        ),
    ]
