# Generated by Django 5.2.13 on 2026-04-15 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_tablearea_area_type'),
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningrecord',
            name='order_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='外部订单号'),
        ),
        migrations.AddField(
            model_name='diningrecord',
            name='source',
            field=models.CharField(choices=[('manual', '手动录入'), ('meituan', '美团收银导入'), ('reservation', '预订到店')], default='manual', max_length=20, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='diningrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dining_records', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AlterUniqueTogether(
            name='diningrecord',
            unique_together={('store', 'order_no')},
        ),
    ]
