# Generated by Django 5.2.13 on 2026-04-14 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_date', models.DateField(verbose_name='提醒日期')),
                ('remind_type', models.CharField(choices=[('birthday', '生日'), ('anniversary', '纪念日'), ('custom', '自定义')], default='custom', max_length=15, verbose_name='提醒类型')),
                ('title', models.CharField(max_length=100, verbose_name='提醒标题')),
                ('message', models.TextField(blank=True, default='', verbose_name='提醒内容')),
                ('days_before', models.PositiveIntegerField(default=3, help_text='提前几天提醒', verbose_name='提前天数')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('handled', '已处理'), ('ignored', '已忽略')], default='pending', max_length=10, verbose_name='状态')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='customers.customer', verbose_name='客户')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '提醒',
                'verbose_name_plural': '提醒',
                'ordering': ['remind_date', '-created_at'],
            },
        ),
    ]
