# Generated by Django 5.2.13 on 2026-04-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='预订日期')),
                ('reservation_time', models.TimeField(verbose_name='预订时间')),
                ('party_size', models.PositiveIntegerField(default=1, verbose_name='预订人数')),
                ('table_number', models.CharField(blank=True, default='', max_length=20, verbose_name='预订桌号')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('arrived', '已到店'), ('cancelled', '已取消'), ('noshow', '未到店')], default='pending', max_length=15, verbose_name='状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='customers.customer', verbose_name='客户')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='customers.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '预订',
                'verbose_name_plural': '预订',
                'ordering': ['-reservation_date', '-reservation_time'],
            },
        ),
    ]
