# Generated by Django 5.2.13 on 2026-04-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_store_tables_count_store_hall_tables_count_and_more'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seat_type',
            field=models.CharField(blank=True, choices=[('hall', '大堂'), ('room', '包间')], default='', help_text='大堂或包间', max_length=10, verbose_name='座位类型'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='customers.tablearea', verbose_name='包间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table_number',
            field=models.CharField(blank=True, default='', help_text='大堂桌号(01,02...)或包间名称', max_length=50, verbose_name='桌号/包间名'),
        ),
    ]
