# Generated by Django 5.2.13 on 2026-04-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_tablearea_area_type'),
        ('reservations', '0002_reservation_seat_type_reservation_table_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seat_type',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table_area',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table_number',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_areas',
            field=models.ManyToManyField(blank=True, help_text='可同时选择多个包间', related_name='reservations', to='customers.tablearea', verbose_name='包间'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_numbers',
            field=models.CharField(blank=True, default='', help_text='多个桌号用逗号分隔，如：01,02,03', max_length=255, verbose_name='大堂桌号'),
        ),
    ]
