# Generated by Django 5.2.13 on 2026-04-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='门店名称')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='门店地址')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('tables_count', models.PositiveIntegerField(default=20, verbose_name='桌位数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否营业')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('category', models.CharField(choices=[('taste', '口味偏好'), ('allergy', '忌口'), ('environment', '环境偏好'), ('consumption', '消费等级'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('color', models.CharField(default='#409EFF', max_length=20, verbose_name='颜色')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('wechat', models.CharField(blank=True, default='', max_length=50, verbose_name='微信号')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('', '未知')], default='', max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('anniversary', models.DateField(blank=True, help_text='如结婚纪念日等', null=True, verbose_name='纪念日')),
                ('level', models.CharField(choices=[('normal', '普通'), ('vip', 'VIP'), ('svip', 'SVIP')], default='normal', max_length=10, verbose_name='客户等级')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.store', verbose_name='常去门店')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tags', to='customers.customer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tags', to='customers.tag')),
            ],
            options={
                'verbose_name': '客户标签',
                'verbose_name_plural': '客户标签',
                'unique_together': {('customer', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, through='customers.CustomerTag', to='customers.tag', verbose_name='标签'),
        ),
    ]
