# Generated by Django 5.2.13 on 2026-04-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='tables_count',
        ),
        migrations.AddField(
            model_name='store',
            name='hall_tables_count',
            field=models.PositiveIntegerField(default=20, help_text='大堂桌子数量，编号自动生成为 01, 02, 03...', verbose_name='大堂桌数'),
        ),
        migrations.CreateModel(
            name='TableArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('room', '包间')], default='room', max_length=10, verbose_name='区域类型')),
                ('name', models.CharField(help_text='如：牡丹厅、VIP包间等，自由命名', max_length=50, verbose_name='包间名称')),
                ('capacity', models.PositiveIntegerField(default=10, verbose_name='可容纳人数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_areas', to='customers.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '座位区域',
                'verbose_name_plural': '座位区域',
                'ordering': ['store', 'id'],
                'unique_together': {('store', 'name')},
            },
        ),
    ]
