# Generated by Django 5.2.13 on 2026-04-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_store_tables_count_store_hall_tables_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablearea',
            name='area_type',
            field=models.CharField(choices=[('room', '包间'), ('hall', '大厅')], default='room', max_length=10, verbose_name='区域类型'),
        ),
    ]
